# version: '3.8'

services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - "../env/.env"
      - "../env/postgres.env"
      - "../env/r2r.env"

    # volumes:
    #   - ../..:/workspaces:cached
    volumes:
      - type: bind
        source: ..
        target: /workspaces/ciayn
        consistency: cached # Or 'consistent' or 'delegated'

    working_dir: /workspaces/ciayn
        
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    image: pgvector/pgvector:pg17
    # profiles: [postgres] #NOTE BUILD: this doesn't work for work for some reason
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: "../env/postgres.env"

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
